name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    env:
      GO_ENV: test
    strategy:
      matrix:
        go_version: ['1.20']
        os: ['ubuntu-latest']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Install
      run: make install

    - name: Create test results directory
      run: mkdir /tmp/test-results

    - name: Test
      run: |
        trap "go-junit-report /tmp/test-results/go-test.out > /tmp/test-results/go-test-report.xml" EXIT
        make test | tee /tmp/test-results/go-test.out && cp coverage.out /tmp/test-results/coverage.out

    - name: Upload test results
      uses: actions/upload-artifact@v3.1.0
      with:
        name: test-results
        path: /tmp/test-results

  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v -o main cmd/main.go
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
    # Artifact name
        name: programa
    # A file, directory or wildcard pattern that describes what to upload
        path: main


  analyze_sonar:
    needs: test
    uses: ./.github/workflows/Sonar.yml
    secrets: inherit

  docker:
    needs: build
    uses: ./.github/workflows/Docker.yml
    secrets: inherit

  deploy_ec2:
    needs: build
    uses: ./.github/workflows/EC2.yml
    secrets: inherit

