name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: Dockerfile
    
    - name: Build Docker Image
      run: docker build -t insta-gift-api .

    - name: Authenticate with AWS ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_PASSWORD_STDIN }}

    - name: Push Docker Image to AWS ECR
      run: |
        docker tag insta-gift-api:latest ${{ secrets.AWS_REGISTRY_URL }}/insta-gift-api:latest
        docker push ${{ secrets.AWS_REGISTRY_URL }}/insta-gift-api:latest
      
    - name: Deploy to AWS ECS
      run: aws ecs update-service --cluster insta-gift-api-cluster --service insta-gift-api-service --force-new-deployment
