name: SonarQube Analysis

on:
  workflow_call:

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Analyze with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: my-custom-directory
          args: >
            -Dsonar.projectKey=insta-gift-api
            -Dsonar.host.url=http://18.191.78.107:9000
            -Dsonar.sources=.
            -Dsonar.test.exclusions=tests/**
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}"
            -Dsonar.pullrequest.branch=${{github.ref_name}}
            -Dsonar.pullrequest.base=master
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
            -Dsonar.qualitygate.wait=true
